// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Ecommerce {
    status:     string;
    request_id: string;
    data:       Datum[];
}

export interface Datum {
    product_id:               string;
    product_title:            string;
    product_description:      string;
    product_photos:           string[];
    product_attributes:       ProductAttributes;
    product_rating:           number | null;
    product_page_url:         string;
    product_offers_page_url:  string;
    product_specs_page_url:   string;
    product_reviews_page_url: string;
    product_num_reviews:      number;
    product_num_offers:       null | string;
    typical_price_range:      string[] | null;
    offer:                    Offer;
}

export interface Offer {
    store_name:             string;
    store_rating:           number | null;
    offer_page_url:         string;
    store_review_count:     number;
    store_reviews_page_url: null | string;
    price:                  string;
    shipping:               string;
    tax:                    string;
    on_sale:                boolean;
    original_price:         null | string;
    product_condition:      ProductCondition;
    buy_now_url?:           string;
}

export enum ProductCondition {
    New = "NEW",
}

export interface ProductAttributes {
    Department?:           string;
    Size:                  string;
    Material?:             string;
    Features?:             string;
    "Closure Style"?:      ClosureStyle;
    Color?:                string;
    Style?:                Style;
    "Toe Style"?:          string;
    "Toddler Department"?: string;
    "Athletic Style"?:     string;
}

export enum ClosureStyle {
    LaceUp = "Lace-up",
    LaceUpHookAndLoop = "Lace-up, Hook and Loop",
}

export enum Style {
    Casual = "Casual",
}
